services:
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      # 映射端口，宿主机3306端口映射到容器3306端口
      - 3306:3306
    volumes:
      - ./script/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: